validate ego vehicle role name
jpc/carlafox pull request #1
Opened 2022-04-15 12:47 UTC by makaveli10

- validate ego vehicle role name with CARLA server and available ros bridge role names

2022-04-15 13:36 UTC, jpc requested changes

2022-04-15 13:36 UTC, jpc commented on notebooks/CARLA 💜 Foxglove demo.ipynb
> +    "                            already exist in the simulation.\")\n",
The `\` in Python strings does not strip the spaces at the beginning of the next line so you get strange long gaps in the output:
```
Given role_name: ego_vehicle already exists in simulation...                         selecting a different one!
```

I would stick to a single line here even if it is a bit long. (or `+` two strings in two lines)

2022-04-15 13:36 UTC, jpc commented on notebooks/CARLA 💜 Foxglove demo.ipynb
> +    "used_role_name = []\n",
This is some global state but inside the function you actually check it every time against the CARLA server. It looks like you could simplify the function quite a bit if you removed this.

It looks to me you could change `get_new_role_name` to create a copy of the possible names list, iterate over CARLA actors to remove the names that are already used, and then use the first one that's left (or choose one at random). The `validate_rolename` would not be required anymore.

2022-04-15 13:40 UTC, makaveli10 commented on notebooks/CARLA 💜 Foxglove demo.ipynb
> +    "used_role_name = []\n",
makes sense. thanks

2022-04-18 15:13 UTC, makaveli10 commented on notebooks/CARLA 💜 Foxglove demo.ipynb
> +    "print(f\"Validated role_name: {role_name}\")\n",
sure, not breaking anything.

2022-04-18 15:15 UTC, makaveli10 commented on notebooks/CARLA 💜 Foxglove demo.ipynb
> +    "ego_vehicle_role_name = [\"ego\", \"hero\", \"ego_vehicle\", \"hero0\", \"hero1\", \"hero2\", \"hero3\", \"hero4\", \"hero5\", \"hero6\", \"hero7\", \"hero8\", \"hero9\"]\n",
yes, sure can do that. Also, we need to extend the role_names with the bridge as well.

2022-04-18 15:16 UTC, zoq commented on notebooks/CARLA 💜 Foxglove demo.ipynb
> +    "ego_vehicle_role_name = [\"ego\", \"hero\", \"ego_vehicle\", \"hero0\", \"hero1\", \"hero2\", \"hero3\", \"hero4\", \"hero5\", \"hero6\", \"hero7\", \"hero8\", \"hero9\"]\n",
True, the ros-bridge needs to be updates as well.

2022-04-18 15:19 UTC, makaveli10 commented on notebooks/CARLA 💜 Foxglove demo.ipynb
> +    "ego_vehicle_role_name = [\"ego\", \"hero\", \"ego_vehicle\", \"hero0\", \"hero1\", \"hero2\", \"hero3\", \"hero4\", \"hero5\", \"hero6\", \"hero7\", \"hero8\", \"hero9\"]\n",
so, the bridge creates an instance of ```EgoVehicle``` only if the given role_name exist within the list the bridge has.

2022-04-18 15:38 UTC, zoq commented on notebooks/CARLA 💜 Foxglove demo.ipynb
> +    "ego_vehicle_role_name = [\"ego\", \"hero\", \"ego_vehicle\", \"hero0\", \"hero1\", \"hero2\", \"hero3\", \"hero4\", \"hero5\", \"hero6\", \"hero7\", \"hero8\", \"hero9\"]\n",
Yeah, so I guess just bump the number of role names someone can use, and keep it simple e.g. `hero0, hero1, ... , heron`.

2022-04-18 15:39 UTC, zoq commented on notebooks/CARLA 💜 Foxglove demo.ipynb
> +    "ego_vehicle_role_name = [\"ego\", \"hero\", \"ego_vehicle\", \"hero0\", \"hero1\", \"hero2\", \"hero3\", \"hero4\", \"hero5\", \"hero6\", \"hero7\", \"hero8\", \"hero9\"]\n",
I guess we could also go for `col0, col1, coln` to brand it a little bit?

2022-04-19 05:29 UTC, makaveli10 commented on notebooks/CARLA 💜 Foxglove demo.ipynb
> +    "ego_vehicle_role_name = [\"ego\", \"hero\", \"ego_vehicle\", \"hero0\", \"hero1\", \"hero2\", \"hero3\", \"hero4\", \"hero5\", \"hero6\", \"hero7\", \"hero8\", \"hero9\"]\n",
yeah sounds good!

2022-04-25 19:51 UTC, jpc requested changes

2022-04-25 19:51 UTC, jpc commented on notebooks/CARLA 💜 Foxglove demo.ipynb
> +   },
This metadata is not really useful but makes diffs harder to read. It should be removed automatically if you run `python cleanup-notebook.py notebooks/CARLA\ 💜\ Foxglove\ demo.ipynb` before committing.

2022-04-25 19:51 UTC, jpc commented on notebooks/CARLA 💜 Foxglove demo.ipynb
> +    "    return role_name"
💜👍

2022-04-27 07:17 UTC, merged